<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxs2KOP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxs2KOP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxs2KOP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxs2KOP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDxs2KOP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dxs2KOP',
    'container.build_id' => '361f72f8',
    'container.build_time' => 1744647428,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxs2KOP');
