<?php

namespace ContainerE8bVeoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qS6acth.App\Entity\Trajet' shared service.
     *
     * @return \App\Entity\Trajet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qS6acth": it needs an instance of "App\\Entity\\Trajet" but this type has been excluded in "config/services.yaml".');
    }
}
