<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dlWO762.App\Controller\TrajetController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dlWO762.App\\Controller\\TrajetController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
        ], [
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
        ]))->withContext('App\\Controller\\TrajetController::index()', $container);
    }
}
