<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kZ4CAju.App\Controller\TrajetController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.kZ4CAju'] ?? $container->load('get_ServiceLocator_KZ4CAjuService'));

        if (isset($container->privates['.service_locator.kZ4CAju.App\\Controller\\TrajetController::edit()'])) {
            return $container->privates['.service_locator.kZ4CAju.App\\Controller\\TrajetController::edit()'];
        }

        return $container->privates['.service_locator.kZ4CAju.App\\Controller\\TrajetController::edit()'] = $a->withContext('App\\Controller\\TrajetController::edit()', $container);
    }
}
