<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KzqlIsCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KzqlIsC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KzqlIsC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transport' => ['privates', '.errored..service_locator.KzqlIsC.App\\Entity\\Transport', NULL, 'Cannot autowire service ".service_locator.KzqlIsC": it needs an instance of "App\\Entity\\Transport" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'transport' => 'App\\Entity\\Transport',
            'entityManager' => '?',
        ]);
    }
}
