<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NwuoA8FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NwuoA8F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NwuoA8F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FrontController::showTransports' => ['privates', '.service_locator.egipcEH.App\\Controller\\FrontController::showTransports()', 'getFrontControllershowTransportsService', true],
            'App\\Controller\\TrajetController::index' => ['privates', '.service_locator.dlWO762.App\\Controller\\TrajetController::index()', 'getTrajetControllerindexService', true],
            'App\\Controller\\TrajetController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\TrajetController::new()', 'getTrajetControllernewService', true],
            'App\\Controller\\TrajetController::show' => ['privates', '.service_locator.qS6acth.App\\Controller\\TrajetController::show()', 'getTrajetControllershowService', true],
            'App\\Controller\\TrajetController::edit' => ['privates', '.service_locator.kZ4CAju.App\\Controller\\TrajetController::edit()', 'getTrajetControllereditService', true],
            'App\\Controller\\TrajetController::delete' => ['privates', '.service_locator.kZ4CAju.App\\Controller\\TrajetController::delete()', 'getTrajetControllerdeleteService', true],
            'App\\Controller\\TransportController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\TransportController::index()', 'getTransportControllerindexService', true],
            'App\\Controller\\TransportController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\TransportController::new()', 'getTransportControllernewService', true],
            'App\\Controller\\TransportController::show' => ['privates', '.service_locator.onDPzYR.App\\Controller\\TransportController::show()', 'getTransportControllershowService', true],
            'App\\Controller\\TransportController::edit' => ['privates', '.service_locator.KzqlIsC.App\\Controller\\TransportController::edit()', 'getTransportControllereditService', true],
            'App\\Controller\\TransportController::delete' => ['privates', '.service_locator.KzqlIsC.App\\Controller\\TransportController::delete()', 'getTransportControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FrontController:showTransports' => ['privates', '.service_locator.egipcEH.App\\Controller\\FrontController::showTransports()', 'getFrontControllershowTransportsService', true],
            'App\\Controller\\TrajetController:index' => ['privates', '.service_locator.dlWO762.App\\Controller\\TrajetController::index()', 'getTrajetControllerindexService', true],
            'App\\Controller\\TrajetController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\TrajetController::new()', 'getTrajetControllernewService', true],
            'App\\Controller\\TrajetController:show' => ['privates', '.service_locator.qS6acth.App\\Controller\\TrajetController::show()', 'getTrajetControllershowService', true],
            'App\\Controller\\TrajetController:edit' => ['privates', '.service_locator.kZ4CAju.App\\Controller\\TrajetController::edit()', 'getTrajetControllereditService', true],
            'App\\Controller\\TrajetController:delete' => ['privates', '.service_locator.kZ4CAju.App\\Controller\\TrajetController::delete()', 'getTrajetControllerdeleteService', true],
            'App\\Controller\\TransportController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\TransportController::index()', 'getTransportControllerindexService', true],
            'App\\Controller\\TransportController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\TransportController::new()', 'getTransportControllernewService', true],
            'App\\Controller\\TransportController:show' => ['privates', '.service_locator.onDPzYR.App\\Controller\\TransportController::show()', 'getTransportControllershowService', true],
            'App\\Controller\\TransportController:edit' => ['privates', '.service_locator.KzqlIsC.App\\Controller\\TransportController::edit()', 'getTransportControllereditService', true],
            'App\\Controller\\TransportController:delete' => ['privates', '.service_locator.KzqlIsC.App\\Controller\\TransportController::delete()', 'getTransportControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\FrontController::showTransports' => '?',
            'App\\Controller\\TrajetController::index' => '?',
            'App\\Controller\\TrajetController::new' => '?',
            'App\\Controller\\TrajetController::show' => '?',
            'App\\Controller\\TrajetController::edit' => '?',
            'App\\Controller\\TrajetController::delete' => '?',
            'App\\Controller\\TransportController::index' => '?',
            'App\\Controller\\TransportController::new' => '?',
            'App\\Controller\\TransportController::show' => '?',
            'App\\Controller\\TransportController::edit' => '?',
            'App\\Controller\\TransportController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\FrontController:showTransports' => '?',
            'App\\Controller\\TrajetController:index' => '?',
            'App\\Controller\\TrajetController:new' => '?',
            'App\\Controller\\TrajetController:show' => '?',
            'App\\Controller\\TrajetController:edit' => '?',
            'App\\Controller\\TrajetController:delete' => '?',
            'App\\Controller\\TransportController:index' => '?',
            'App\\Controller\\TransportController:new' => '?',
            'App\\Controller\\TransportController:show' => '?',
            'App\\Controller\\TransportController:edit' => '?',
            'App\\Controller\\TransportController:delete' => '?',
        ]);
    }
}
