<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KZ4CAjuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kZ4CAju' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kZ4CAju'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajet' => ['privates', '.errored..service_locator.kZ4CAju.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.kZ4CAju": it needs an instance of "App\\Entity\\Trajet" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'trajet' => 'App\\Entity\\Trajet',
            'entityManager' => '?',
        ]);
    }
}
