<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KzqlIsC.App\Controller\TransportController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.KzqlIsC'] ?? $container->load('get_ServiceLocator_KzqlIsCService'));

        if (isset($container->privates['.service_locator.KzqlIsC.App\\Controller\\TransportController::edit()'])) {
            return $container->privates['.service_locator.KzqlIsC.App\\Controller\\TransportController::edit()'];
        }

        return $container->privates['.service_locator.KzqlIsC.App\\Controller\\TransportController::edit()'] = $a->withContext('App\\Controller\\TransportController::edit()', $container);
    }
}
