<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KzqlIsC.App\Entity\Transport' shared service.
     *
     * @return \App\Entity\Transport
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KzqlIsC": it needs an instance of "App\\Entity\\Transport" but this type has been excluded in "config/services.yaml".');
    }
}
