<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qS6acth.App\Controller\TrajetController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qS6acth.App\\Controller\\TrajetController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajet' => ['privates', '.errored..service_locator.qS6acth.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.qS6acth": it needs an instance of "App\\Entity\\Trajet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'trajet' => 'App\\Entity\\Trajet',
        ]))->withContext('App\\Controller\\TrajetController::show()', $container);
    }
}
