<?php

namespace ContainerDxs2KOP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kZ4CAju.App\Controller\TrajetController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kZ4CAju.App\\Controller\\TrajetController::delete()'] = ($container->privates['.service_locator.kZ4CAju'] ?? $container->load('get_ServiceLocator_KZ4CAjuService'))->withContext('App\\Controller\\TrajetController::delete()', $container);
    }
}
