<?php

namespace ContainerOW9DUDp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4qjl4DKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4qjl4DK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4qjl4DK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AvatarController::viewAvatar' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\RegistrationController::updateAvatar3D' => ['privates', '.service_locator.91QYP5y', 'get_ServiceLocator_91QYP5yService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.GBTTJY6', 'get_ServiceLocator_GBTTJY6Service', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::DeleteUser' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController::ShowUser' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::ajouterUser' => ['privates', '.service_locator.5020tIq', 'get_ServiceLocator_5020tIqService', true],
            'App\\Controller\\UserController::banUser' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController::modifierUser' => ['privates', '.service_locator.c24g2ds', 'get_ServiceLocator_C24g2dsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AvatarController:viewAvatar' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\RegistrationController:updateAvatar3D' => ['privates', '.service_locator.91QYP5y', 'get_ServiceLocator_91QYP5yService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.GBTTJY6', 'get_ServiceLocator_GBTTJY6Service', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:DeleteUser' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController:ShowUser' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:ajouterUser' => ['privates', '.service_locator.5020tIq', 'get_ServiceLocator_5020tIqService', true],
            'App\\Controller\\UserController:banUser' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController:modifierUser' => ['privates', '.service_locator.c24g2ds', 'get_ServiceLocator_C24g2dsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AvatarController::viewAvatar' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::updateAvatar3D' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::DeleteUser' => '?',
            'App\\Controller\\UserController::ShowUser' => '?',
            'App\\Controller\\UserController::ajouterUser' => '?',
            'App\\Controller\\UserController::banUser' => '?',
            'App\\Controller\\UserController::modifierUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AvatarController:viewAvatar' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:updateAvatar3D' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:DeleteUser' => '?',
            'App\\Controller\\UserController:ShowUser' => '?',
            'App\\Controller\\UserController:ajouterUser' => '?',
            'App\\Controller\\UserController:banUser' => '?',
            'App\\Controller\\UserController:modifierUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
